### ISSUE TITLE
standalone version

### ISSUE THREAD

**Issue by shuvalov-anton** [mrsum/backbone-notify#1]
You can build standalone valid es5 version that can be used with either commonjs, requirejs and without the one. Just checkout `browserify --standalone` flag. For example:

```shell
browserify -t jadeify -t babelify index.js --standalone notify -o notify.dest.js
```

**Comment by mrsum** [comment]
Sure, please get new version of backbone-notify and U can use: 
```bash
gulp build
```
for building standalone version without vendors, or check dist dir inside this repo.
